import Head from "next/head";
import Stairs from "@/components/layout/Stairs";
import building from "@/assets/building.jpeg";
import Image from "next/image";

const About = () => {
  return (
    <>
      <Head>
        <title>Page Transitions Stairs</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/icon.svg" />
      </Head>
      <Stairs>
        <h1 className="text-3xl pt-5">Stairs</h1>
        <div className="flex mt-5 gap-5 flex-col md:flex-row ">
          <Image
            src={building}
            alt="tulum"
            className="w-1/2 h-1/3 object-contain rounded-md "
          />
          <div className="flex flex-col p-2 rounded-md gap-3">
            <p>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent
              imperdiet nibh sit amet velit dignissim, non tempus nisl
              pellentesque. Praesent sagittis magna sit amet ex blandit, id
              pharetra lectus feugiat. Praesent sit amet congue ipsum, in
              ultrices neque. In dapibus in purus vitae dignissim.
            </p>
            <button className="bg-black text-white font-bold w-32 p-3 rounded-lg mt-5">
              Click
            </button>
            <h2 className=" font-extrabold text-gray-200 text-3xl">01</h2>
            <p className="w-96 text-gray-500">
              Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent
              imperdiet nibh sit amet velit dignissim, non tempus nisl
              pellentesque. Praesent sagittis magna sit amet ex blandit,
            </p>{" "}
            <h2 className=" font-extrabold text-gray-200 text-3xl">02</h2>
            <p className="w-96 text-gray-500">
              Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent
              imperdiet nibh sit amet velit dignissim, non tempus nisl
              pellentesque. Praesent sagittis magna sit amet ex blandit,
            </p>{" "}
          </div>
        </div>
      </Stairs>
    </>
  );
};

export default About;
